### ISSUE TITLE
Battery drains in 4 days

### ISSUE THREAD

**Issue by JeroenTuinstra** [owenb321/eink_ambient_display#1]
Was just wondering how long your display lasts? Mine only lastst 4 days. I can post the code or if you want this it he link at esphome forum: 

[https://community.home-assistant.io/t/battery-empty-after-4-days-should-be-longer/492159](url)

Help would greatly appreciated

**Comment by owenb321** [comment]
I get about 2 weeks with a 2500mah LiPo. Theoretically it should be longer and I think the issue may be with the e-ink display still using power while the ESP is sleeping, but I haven't taken the time to track down where the power draw is coming from.

**Comment by owenb321** [comment]
I resolved this with a hardware change. Adding a [TPL5111](https://www.adafruit.com/product/3573) timer cuts off the power to the Waveshare display between updates which dramatically reduced power usage. I'm now getting ~3 months of battery life with a 2500mah LiPo. The main branch is now updated with the ESPHome config for utilizing this timer module.
