### ISSUE TITLE
do you have a configuration on how to push this sensors to mqtt

### ISSUE THREAD

**Issue by langerma** [owenb321/eink_ambient_display#2]
i tried to use this for my home but i am not a c++ 
programmer and i cannot figure out which format all these sensors have to be in mqtt

do you have an example config for this?

kind regards

**Comment by owenb321** [comment]
Here's a gist of how I'm pushing some of these sensors in Home Assistant

[epaper_sensors-yaml](https://gist.github.com/owenb321/3a1caad7bbbfdebaf21a7f56c705fa58#file-epaper_sensors-yaml)

**Comment by langerma** [comment]
thx that solved my issue :-)
